### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by presingjos** [presingjos/Joe-Chat#2]
- [ ] Clean up CSS and HTML
- [ ] Add docstrings to javascript function (adhere to standard js)
- [ ] Link server url to client (ie remove hard coded localhost...)
